[package]
name = "sdb_signal"
version = "0.1.0"
edition = "2021"
authors = ["Mike Yang <yfractal@gmail.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.169"
magnus = { version = "0.6.2" }
